services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - mysql_test
    environment:
      - YII_ENV=dev
      - YII_DEBUG=1
      - DB_DSN=mysql:host=mysql;dbname=book_catalog
      - DB_USERNAME=book_user
      - DB_PASSWORD=book_password
      - TEST_DB_DSN=mysql:host=mysql_test;dbname=book_catalog_test
      - TEST_DB_USERNAME=test_user
      - TEST_DB_PASSWORD=test_password
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=book_catalog
      - MYSQL_USER=book_user
      - MYSQL_PASSWORD=book_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

  mysql_test:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=book_catalog_test
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_password
      - MYSQL_ROOT_PASSWORD=test_root_password
    volumes:
      - mysql_test_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - app-network
    tmpfs:
      - /var/lib/mysql:noexec,nosuid,size=1024m

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  mysql_test_data:
